# Generated by Django 2.2.6 on 2019-10-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nutri_score', models.CharField(max_length=1)),
                ('barcode', models.CharField(max_length=13)),
                ('picture', models.ImageField(upload_to='images/')),
                ('category_product', models.ManyToManyField(related_name='products', to='catalog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nutri_score', models.CharField(max_length=1)),
                ('barcode', models.CharField(max_length=13)),
                ('url', models.URLField()),
                ('nutrition', models.ImageField(upload_to='images/')),
                ('picture', models.ImageField(upload_to='images/')),
                ('product_substitute', models.ManyToManyField(related_name='substitute', to='catalog.Product')),
            ],
        ),
    ]
