# Generated by Django 2.2.6 on 2019-10-18 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_product',
        ),
        migrations.RemoveField(
            model_name='substitute',
            name='barcode',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category'),
            preserve_default=False,
        ),
    ]
