# Generated by Django 2.2.6 on 2019-10-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191018_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitute',
            name='barcode',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
