# Generated by Django 2.2.6 on 2019-10-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_substitute_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substitute',
            old_name='product_substitute',
            new_name='composition',
        ),
    ]
