# Generated by Django 2.2.6 on 2019-10-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191020_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='barcode',
            field=models.CharField(max_length=30),
        ),
    ]
