# Generated by Django 2.2.6 on 2019-10-26 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_auto_20191020_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitute',
            name='user_sub',
            field=models.ManyToManyField(related_name='user_substitute', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='composition',
            field=models.ManyToManyField(related_name='substitutes', to='catalog.Product'),
        ),
    ]
